version: "3.7"
services:
  mongo:
    image: 'mongo:4.2-bionic'
    ports:
      - '27017:27017'
    volumes:
      - './tmp/db:/data/db'
  backend:
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - mongo
